# Verwende das offizielle Microsoft .NET SDK-Image als Basis-Image
FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build-env

# Setze das Arbeitsverzeichnis im Container
WORKDIR /app

# Kopiere die CSPROJ-Datei und stelle die .NET-Abhängigkeiten wieder her
COPY *.csproj ./
RUN dotnet restore

# Kopiere den restlichen Quellcode in den Container
COPY . ./

# Kompiliere die Anwendung
RUN dotnet publish -c Release -o out

# Verwende das offizielle Microsoft .NET Runtime-Image für das laufende Image
FROM mcr.microsoft.com/dotnet/aspnet:7.0

# Setze das Arbeitsverzeichnis im Container
WORKDIR /app

# Kopiere die kompilierte Anwendung aus dem Build-Container
COPY --from=build-env /app/out .

# Setze die Umgebungsvariable, die angibt, dass die Anwendung im Container läuft
ENV ASPNETCORE_URLS=http://+:80

# Öffne Port 80 für den HTTP-Verkehr
EXPOSE 80

# Führe die Anwendung aus
ENTRYPOINT ["dotnet", "Modul295_SkiService_WebAPI.dll"]
